#!/bin/sh

uri=$(cat ~/etc/secret/update-dns.uri)
tmp=$(mktemp -t update-dns.XXXXXXXXXX)
trap "rm -f '$tmp'" EXIT KILL INT

curl -Ls "$uri" | tee "$tmp"

grep -qx '^No IP change detected for .*, skipping update$' "$tmp"
